/** Mock catalog for skill search (replace with API later). */
export const MOCK_SKILL_SUGGESTIONS: string[] = [
  "JavaScript",
  "TypeScript",
  "ReactJS",
  "Next.js",
  "NodeJS",
  "Express.js",
  "MongoDB",
  "PostgreSQL",
  "Redis",
  "GraphQL",
  "REST APIs",
  "Microservices",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "GCP",
  "RabbitMQ",
  "Kafka",
  "React Native",
  "Flutter",
  "Java",
  "Spring Boot",
  "Python",
  "Django",
  "FastAPI",
  "Go",
  "Rust",
  "C#",
  ".NET",
  "SQL",
  "Elasticsearch",
  "System design",
  "CI/CD",
  "Git",
];
